
import { paths, components } from "./schema"; // <- generated by openapi-typescript

// Schema Obj
type Post = components["schemas"]["posts"];

const post: Post = {};

type Page = paths["/pages/slug/{slug}"]["get"]["responses"]["200"]["content"]["application/json"]["pages"]

