type: object
properties:
  pagination:
    type: object
    properties:
      page:
        type: number
      limit:
        oneOf:
          - type: number
          - type: string
            pattern: ^all$
      pages:
        type: number
      total:
        type: number
      next:
        type: string
        nullable: true
      prev:
        type: string
        nullable: true
